### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Dingenis** [Dingenis/jv2#1]
# <h1>Server Side</h1>

Assignee: @Area348 

---

**Zie:** _Jotihunt API V2.0 - handleiding voor API-Calls_

---

**API-Calls:** _ChangeLOG / ToDo's_

_Vos:_
- [x] Spots/Hunts melden.
- [x] vos/SLEUTEL/{team}/all/{time}
- [x] Geef 0 terug als er geen hint_nr is.

_Hunter:_
- [x] /hunter/SLEUTEL/all/{time}
- [X]  /hunter/SLEUTEL/naam/tail/{naam}/{time}
- [X] /hunter/SLEUTEL/andere/{gebruiker}/{time}
- [x] Onregelmatigheid door het verschillende gebruik van "hunter" of "gebruiker" met dezelfde betekenis.

_Login:_
- [x] Bann funtie op ip niveau.
- [X] WhiteList op ip niveau.
- [X] login/SLEUTEL/{eigen info} (bv.: Avatar, Naam, Rechten, etc)

_Analytics:_
- [x] Google Analytics toegevoegd aan de API en de website.
- [x] Access_LOG weer aangezet voor test / analytics doel einde, !!! deze kan de site vertragen als hij te vol komt, dus even in de gaten houden !!!

_FCM:_
- [x] API SLEUTEL check "True/False".
- [x] FCM Priority High
- [x] FCM TOKEN toevoegen in db.
- [x] API check of FCM TOKEN + GEBRUIKER bestaat.
- [x] API FCM TOKEN toevoegen in db.
- [x] API FCM TOKEN updaten in db.
- [ ] SITE function TOKEN set?
- [ ] SITE function to sent FCM text.
- [ ] Site FCM bericht sturen (text).
- [ ] Iet voor mattijn en zn TG bot fixen....
- [x] DOCS: Coördinaat vos versturen ICON check!!!!

---

<h1>Client Side</h1>

Assignees: @Dingenis, (@njittam)?
- [ ] Auto Gebied Detectie, automatisch herkennen op welk vossen team de gebruiker hunt, door te kijken of zijn locatie voorkomt in een van de deelgebied polygons. Gebruik hier voor `PolyUtil.containsLocation()`
- [ ] Smart Sync, het slim ophalen en verwerken van gegevens. Bijvoorbeeld de ScoutingGroep data is eigenlijk statisch(een ScoutingGroep gaat niet verplaatsen). Dus eigenlijk hoeft de data maar een keer opgehaald te worden en daarna opgeslagen te worden. Ook zorgt Smart Sync bijvoorbeeld voor het slim(om de 60s) verzenden van de gebruikers locatie naar de server. Eigenlijk alles wat te maken heeft met ophalen en verzenden maar dat geautomatiseerd.
- [x] Gebruikers informatie, het ophalen van gebruikers info.
- [x] Alle data moet offline kunnen worden opgeslagen als cache voor later.
  **UPDATE: Nu mogelijk met:**  `MapStorageReadTask` en `MapStorageUtil`
- [ ] Smart View, het slim bekijken van de map. Laat bijvoorbeeld alleen het gebied zien waarin je aan het hunten bent.
- [ ] Zoekfunctie, er moet gezocht kunnen worden naar verschillende items zoals Scoutinggroepen, hunters, etc.
- [x] Filteren van de map, alle items op de map moeten zichtbaar en onzichtbaar gemaakt kunnen worden. **UPDATE: Nu mogelijk met:** `MapFilter`  
- [ ] Tracker, het volgen van de gebruiker op de map en een spoor achter laten.
- [ ] Code cleanup, het beter maken en netjes maken van de code.
- [ ] Documentatie, een duidelijk documentatie over het Client project.
- [ ] Automatische vergroting cirkels vossen. 

<h1>Bot</h1>

Assignees: @njittam 

<h1>Design</h1>

Assignees: @Dingenis, @njittam, @Area348, @jesse_____
- [ ] Nieuwe iconen voor: hunters, en meer?

<h1>Tools</h1>

Assignees: @Dingenis, @njittam, @Area348 
- [x] KML Converter, het jotihunt kml bestand om te zetten naar ScoutingGroep formaat zoals op de server, en om de deelgebied polygons eruit te halen.
- [x] API Tester, programma om de api te testen (zie JotiApiT repo)

**Comment by Area348** [comment]
Zo weer wat werk verzet in de API, dank zij de API-T van Bram kan ik nu ook de POST verzoeken testen :D

Vul het bovenstaande lijstje maar aan (wel graag in de huidige opbouw zo als ik het nu gemaakt heb ) voor wat er nog meer moet komen/veranderd moet worden ;).

**Comment by Area348** [comment]
Nou alle API GET/POST Call's zijn gemaakt ;)

Als ik er meer moet maken hoor ik dat graag, anders kan ik beginnen met rewrite van de site...
Dat gaat nog een in mens werk worden.... en ik weet ook niet of ik dat wel voor de hunt klaar heb, daarom ga ik de huidige versie nog maar niet offline halen ;)...
